# This action will update the latest code change in folder scripts to the S3
# bucket to be used by the Lambda function
name: compile/zip and upload to S3

on:
  push:
    branches: [ "master" ]
    paths: 'scripts/**'
#  pull_request:
#    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to check out the code from the repo


jobs:
  upload:
    name: setting up the environment
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      BASE_PATH: scripts
      PY_FILENAME: ec2_cleanup.py


    steps:
    - uses: actions/checkout@v3

    - name: Set up Go environment
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build Go binary
      run: |
        cd $BASE_PATH
        go mod init ec2_backup
        go mod tidy
        GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w"

    - name: Create folders for zip
      run: |
        cd $BASE_PATH
        mkdir ec2_backup_go
        mv ec2_backup ec2_backup_go/
        mkdir ec2_cleanup
        mv $PY_FILENAME ec2_cleanup/

    - name: Zip Go binary
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r ec2_backup.zip scripts/ec2_backup_go

    - name: Zip Python file
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r ec2_cleanup.zip scripts/ec2_cleanup

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        role-duration-seconds: 900
        aws-region: ${{ env.AWS_REGION }}

    - name: Upload Zipped files to S3
      run: |
        aws s3 cp ec2_backup.zip ${{ secrets.S3_BUCKET }}/scripts/
        aws s3 cp ec2_cleanup.zip ${{ secrets.S3_BUCKET }}/scripts/

    - name: List S3
      run: aws s3 ls ${{ secrets.S3_BUCKET }}/scripts --recursive --human-readable --summarize

    - name: Deploying Go Backup Lambda function
      run: |
        aws lambda update-function-code --function-name backup_ec2_lambda --s3-bucket "s3-lambda-20221018154517921000000002" --s3-key scripts/ec2_backup.zip
        aws lambda update-function-code --function-name cleanup_ec2_lambda --s3-bucket "s3-lambda-20221018154517921000000002" --s3-key scripts/ec2_cleanup.zip
